import * as THREE from './vendor/three.module.js?v=20260930-rootfix-1';
import {GLTFLoader} from './vendor/GLTFLoader.js?v=20260930-rootfix-1';

const canvas=document.querySelector('#world'), renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.55;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color('#24130d');scene.fog=new THREE.FogExp2('#24130d',.028);
const camera=new THREE.PerspectiveCamera(36,1,.05,100);const target=new THREE.Vector3();
scene.add(new THREE.HemisphereLight('#fff3d6','#8f3c25',2.35));
const key=new THREE.DirectionalLight('#ffe2ae',3.6);key.position.set(-3,7,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;scene.add(key);
const rim=new THREE.PointLight('#f86140',35,18);rim.position.set(4,2,-3);scene.add(rim);
const fill=new THREE.PointLight('#ffedc3',16,15);fill.position.set(2,4,5);scene.add(fill);
const floor=new THREE.Mesh(new THREE.CircleGeometry(5,96),new THREE.MeshStandardMaterial({color:'#432318',roughness:.92}));floor.rotation.x=-Math.PI/2;floor.position.y=-.78;floor.receiveShadow=true;scene.add(floor);
const disc=new THREE.Mesh(new THREE.CylinderGeometry(2.05,2.14,.18,96),new THREE.MeshStandardMaterial({color:'#743b25',roughness:.78,metalness:.08}));disc.position.y=-.68;disc.receiveShadow=true;scene.add(disc);
const strandPoints=[];for(let i=0;i<90;i++){let t=i/89;strandPoints.push(new THREE.Vector3(Math.sin(t*12)*(.25+t*.85),.25+t*2.9,Math.cos(t*10)*(.15+t*.6)-.4))}
const strandCurve=new THREE.CatmullRomCurve3(strandPoints);const strand=new THREE.Mesh(new THREE.TubeGeometry(strandCurve,260,.023,8,false),new THREE.MeshStandardMaterial({color:'#ffc453',emissive:'#b65e19',emissiveIntensity:.55,roughness:.34,metalness:.08}));scene.add(strand);
const sparkGeometry=new THREE.BufferGeometry();const sparkPositions=new Float32Array(180*3);for(let i=0;i<180;i++){sparkPositions[i*3]=(Math.random()-.5)*10;sparkPositions[i*3+1]=Math.random()*5-.5;sparkPositions[i*3+2]=(Math.random()-.5)*8}sparkGeometry.setAttribute('position',new THREE.BufferAttribute(sparkPositions,3));const sparks=new THREE.Points(sparkGeometry,new THREE.PointsMaterial({color:'#e7ae65',size:.025,transparent:true,opacity:.48,depthWrite:false}));scene.add(sparks);
const gltf=new GLTFLoader(),modelNames={mac:'mac-bowl',pasta:'zos-pasta-bowl-old',fork:'fork-pasta',olives:'olive-pair',mushrooms:'mushrooms',meat:'extra-meat',cheese:'extra-cheese'};
const models={},animated={},addons=new Set();let flavour='mac',progress=0,pointerX=0,drag=0,isDragging=false,loaded=0,ready=false;
const positions={black:[-1.45,1.06,.2],green:[-1.05,1.3,-.8],mushrooms:[1.2,1.15,-.8],meat:[1.5,.85,.4],cheese:[.1,1.6,-1.2]};
const ease=(a,b,t)=>a+(b-a)*Math.min(1,Math.max(0,t));const clamp=t=>Math.min(1,Math.max(0,t));
const loadBar=document.querySelector('#load-bar'),loadLabel=document.querySelector('#load-label');
function setLoadProgress(name,fraction=0){const overall=Math.min(1,(loaded+clamp(fraction))/7);loadBar.style.transform=`scaleX(${overall})`;const pct=Math.round(clamp(fraction)*100);loadLabel.textContent=`Loading ${name.replaceAll('-',' ')} · ${pct}% · ${loaded} / 7 ready`}
function loadModel(key,name){return new Promise((resolve,reject)=>{const complete=g=>{try{const root=new THREE.Group(),object=g.scene;const box=new THREE.Box3().setFromObject(object),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());object.position.sub(center);let max=Math.max(size.x,size.y,size.z)||1;object.scale.setScalar((key==='fork'?2.25:key==='mac'||key==='pasta'?2.85:1.08)/max);root.add(object);root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(Array.isArray(o.material)){o.material.forEach(m=>m.side=THREE.DoubleSide)}else if(o.material){o.material.side=THREE.DoubleSide}}});root.visible=false;scene.add(root);models[key]=root;animated[key]={position:new THREE.Vector3(),scale:1};loaded++;loadBar.style.transform=`scaleX(${loaded/7})`;loadLabel.textContent=`Preparing the ingredients · ${loaded} / 7`;resolve(root)}catch(error){reject(error)}};gltf.load(new URL(`./public/models/${name}.glb`,import.meta.url).href,complete,event=>{if(event.lengthComputable&&event.total>0)setLoadProgress(name,event.loaded/event.total)},error=>reject(new Error(`Could not load local model ${name}.glb`,{cause:error})))})}
function setupOlives(){models.black=models.olives;models.green=models.olives.clone(true);scene.add(models.green);models.black.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.color.multiply(new THREE.Color('#5e5b51'))}});models.green.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.color.multiply(new THREE.Color('#b6c76b'))}})}
function enter(){document.querySelector('#loading').classList.add('done')}
const first=loadModel('mac',modelNames.mac).then(model=>{model.visible=true;ready=true;enter();return model}).catch(e=>{console.error('First bowl unavailable',e);loadLabel.textContent='The first bowl could not load. Open the console for the exact error.';enter()});
first.finally(()=>{const loadKeys=async keys=>{for(const k of keys){if(models[k])continue;try{await loadModel(k,modelNames[k]);if(k==='olives')setupOlives()}catch(e){console.error('Model unavailable',k,e)}}};const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,900));idle(()=>loadKeys(['pasta','fork']),{timeout:2500});const loadAddons=()=>loadKeys(['olives','mushrooms','meat','cheese']);const addonSection=document.querySelector('#addons');if('IntersectionObserver'in window&&addonSection){const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting||entry.boundingClientRect.top<innerHeight*1.8)){observer.disconnect();loadAddons()}},{rootMargin:'120% 0px'});observer.observe(addonSection)}else{setTimeout(loadAddons,3500)}});
document.querySelector('#skip-load').addEventListener('click',enter);
const sections=[...document.querySelectorAll('.chapter')];function getScrollProgress(){const last=document.documentElement.scrollHeight-innerHeight;return last?clamp(scrollY/last):0}
function setProgress(){progress=getScrollProgress();document.querySelector('#progress-bar').style.transform=`scaleX(${progress})`;const idx=Math.min(5,Math.floor(progress*6));document.body.dataset.chapter=sections[idx].id}
addEventListener('scroll',setProgress,{passive:true});addEventListener('resize',resize);setProgress();
document.querySelectorAll('.select-flavour').forEach(button=>button.addEventListener('click',()=>{flavour=button.dataset.flavour;document.querySelectorAll('.select-flavour').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.flavour===flavour)));summary();button.animate([{transform:'scale(.96)'},{transform:'scale(1)'}],{duration:350,easing:'ease-out'})}));
document.querySelectorAll('.choices input').forEach(input=>input.addEventListener('change',()=>{input.checked?addons.add(input.value):addons.delete(input.value);summary()}));
function summary(){document.querySelector('#summary-flavour').textContent=flavour==='mac'?"Zo's Mac n Cheese":"Zo's Pasta";document.querySelector('#summary-addons').textContent=addons.size?'Addons: '+[...addons].map(v=>({black:'black olives',green:'green olives',mushrooms:'mushrooms',meat:'extra meat',cheese:'extra cheese'}[v])).join(', '):'Addons: none selected'}summary();
canvas.addEventListener('pointerdown',e=>{isDragging=true;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',()=>isDragging=false);canvas.addEventListener('pointermove',e=>{pointerX=(e.clientX/innerWidth-.5)*2;if(isDragging)drag+=e.movementX*.008});
const states=[{p:[.3,.6,5.6],t:[0,.9,0],bg:'#24130d',light:1},{p:[2.7,1.5,4.8],t:[0,0,0],bg:'#5b2b16',light:1.2},{p:[-2.4,1.65,4.6],t:[0,.1,0],bg:'#5b1d17',light:1.65},{p:[0,5.1,2.6],t:[0,0,0],bg:'#3a2118',light:1.25},{p:[1.15,1.75,3.05],t:[0,.7,0],bg:'#482315',light:1.8},{p:[2.65,2.05,5.5],t:[0,0,0],bg:'#24130d',light:1.1}];
const cp=new THREE.Vector3(.3,.6,5.6),ct=new THREE.Vector3(0,.9,0),bg=new THREE.Color(),clock=new THREE.Clock(),mobile=()=>innerWidth<800;
function resize(){const dpr=Math.min(devicePixelRatio,mobile()?1.35:1.75);renderer.setPixelRatio(dpr);renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.fov=mobile()?46:36;camera.updateProjectionMatrix()}resize();
function render(){requestAnimationFrame(render);let t=clock.getElapsedTime(),phase=clamp(progress*5),i=Math.min(4,Math.floor(phase)),a=phase-i;if(progress>=.999){i=4;a=1}a=a*a*(3-2*a);let s=states[i],n=states[i+1];const cameraPos=s.p.map((v,j)=>ease(v,n.p[j],a)),cameraTarget=s.t.map((v,j)=>ease(v,n.t[j],a));if(mobile()){cameraPos[0]*=.38;cameraPos[2]*=1.23;cameraTarget[1]+=.18}cp.lerp(new THREE.Vector3(...cameraPos),.055);ct.lerp(new THREE.Vector3(...cameraTarget),.055);camera.position.copy(cp);camera.lookAt(ct);bg.set(s.bg).lerp(new THREE.Color(n.bg),a);scene.background.lerp(bg,.035);scene.fog.color.copy(scene.background);rim.intensity=ease(s.light,n.light,a)*25;
 const chapter=progress*6,showMac=chapter<2.65||chapter>3.2&&flavour==='mac',showPasta=chapter>=1.8&&chapter<3.4||chapter>=3.2&&flavour==='pasta';
 if(models.mac){let m=models.mac;m.visible=showMac;m.position.set(chapter<1?.5*(1-chapter):chapter>2.3&&chapter<3.2?-3*Math.min(1,(chapter-2.3)*2):0,Math.sin(t*1.15)*.025-.02,0);m.scale.setScalar(chapter<.8?.7:.96);m.rotation.y=drag+Math.sin(t*.3)*.05}
 if(models.pasta){let m=models.pasta;m.visible=showPasta;m.position.set(chapter<2?2.5*(2-chapter):0,Math.sin(t*.9)*.025-.02,0);m.scale.setScalar(chapter<2?.78:.96);m.rotation.y=-drag+Math.sin(t*.3)*.05}
 if(models.fork){let m=models.fork;m.visible=chapter<1.3||chapter>3.5;m.position.set(chapter>3.5?.75+Math.sin(t*.7)*.04:1.45,chapter>3.5?1.25+Math.sin(t*1.3)*.13:1.35,-.7);m.scale.setScalar(chapter>3.5?.48:.58);m.rotation.set(.2,-.35+pointerX*.13,chapter>3.5?-.5:-.8)}
 const orbit=Math.max(0,Math.min(1,(chapter-2.7)*1.5));for(const [key,k] of [['black','black'],['green','green'],['mushrooms','mushrooms'],['meat','meat'],['cheese','cheese']]){let m=models[k];if(!m)continue;let selected=addons.has(key),visible=chapter>2.5&&chapter<5.9&&(chapter<4.2||selected);m.visible=visible;if(!visible)continue;let base=positions[key],angle=t*.26+(key==='black'?0:key==='green'?1:key==='mushrooms'?2:key==='meat'?3:4);let x=base[0]+Math.cos(angle)*.13,y=base[1]+Math.sin(t*1.2+angle)*.09,z=base[2];let settle=selected&&chapter>3.4?clamp((chapter-3.4)*1.3):0;m.position.set(ease(x,base[0]*.22,settle),ease(y,.43,settle),ease(z,.08,settle));m.scale.setScalar((key==='green'||key==='black'?.47:.55)*(1-.38*settle)*Math.max(.01,orbit));m.rotation.y=angle+(key==='green'?Math.PI:0)}
 strand.rotation.y=t*.045;strand.material.emissiveIntensity=.4+.16*Math.sin(t*2);strand.visible=chapter<4.8;sparks.rotation.y=t*.008;disc.rotation.y=t*.015;renderer.render(scene,camera)}render();
